### ISSUE TITLE
No way to enter JSON types != strings via browser

### ISSUE THREAD

**Issue by curiositycasualty** [TritonDataCenter/sdc-adminui#233]
Although `adminui` offers an `Edit Metadata` GUI interface, values entered there are always interpreted as json strings.
This renders the `adminui` useless for such tasks as enabling custom image creation (as with the `triton` packer builder) since entering "true" into the `Edit Metadata` interface results in the string literal: "true" rather than the JSON type of `true`.

The only workaround is if you have shell access to the SmartOS headnode and can enter the following directly:
```bash
echo '{"metadata": {"IMGAPI_ALLOW_LOCAL_CREATE_IMAGE_FROM_VM": true}}' \ | sapiadm update $(sdc-sapi /services?name=imgapi | json -H 0.uuid)
```

per https://docs.joyent.com/private-cloud/install/image-management

**Comment by bahamat** [comment]
This is at `/services/:uuid`, but probably also applies to instance metadata as well.

**Comment by curiositycasualty** [comment]
Closing own stale issues.
