### ISSUE TITLE
Request to expose more VM metadata via adminui

### ISSUE THREAD

**Issue by curiositycasualty** [TritonDataCenter/sdc-adminui#234]
Particularly stuff like VNC information.
Or maybe even an HTML 5 virtual terminal across SmartOS's coveted TTY.

Without SSH access to the headnode, one's options for troubleshooting a VM startup/kernel-crash/grub issues is very limited.
Also worth mentioning, the way SmartOS recycles VNC sessions per VM boot makes it particularly unhelpful here.

**Comment by latoile** [comment]
Yes, noVNC integration could be a real benefit for KVM management.
https://github.com/novnc/noVNC

**Comment by curiositycasualty** [comment]
Closing own stale issues.
